# -*- coding: utf-8 -*-
"""recomendação de restaurante.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wf7iH546yDJXuNVTQ419dapAXnT7RwwB
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

def recomenda_restaurante(nome):
  xlsx = pd.ExcelFile('/content/drive/MyDrive/UFABC/Graduação/Engenharia de Software/Projeto Final/base_sintetica.xlsx')
  cliente = pd.read_excel(xlsx, 'cliente')
  reserva = pd.read_excel(xlsx, 'reserva')
  restaurante = pd.read_excel(xlsx, 'restaurante')
  df = cliente.join(reserva.set_index('cliente_id'),on = 'cliente_id').join(restaurante.set_index('restaurante_id'), on = 'restaurante_id')[['cliente_id','cliente_nome','restaurante_id','restaurante_nome','restaurante_categoria']]
  lista = df.loc[df['cliente_nome'] == 'Jessica Gross']['restaurante_categoria'].value_counts().nlargest(2).index
  return lista

recomenda_restaurante('Jessica Gross')